sudo: true
language: cpp
dist: trusty

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

  - os: linux
    compiler: clang
    env:
      - COMPILER=clang++-7.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
        packages: ['g++-8', 'clang-7']

  - os: linux
    language: python
    python: "3.6"
    services:
      - docker
    env:
      - COMPILER=g++-8
      - CONAN_GCC_VERSIONS=8
      - CONAN_DOCKER_IMAGE=lasote/conangcc8
    install:
       - pip install -U conan conan-package-tools
    script:
      - python .conan/build.py

before_install:
  - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install boost || brew upgrade boost
       brew install pcre2 || brew upgrade pcre2
       brew install re2 || brew upgrade re2
     else
       sudo add-apt-repository -y ppa:sergey-dryabzhinsky/packages
       sudo apt-get update -qq
       sudo apt-get install -qq libpcre2-dev libre2-dev libboost-all-dev
     fi

install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - uname -a
  - $CXX --version
script:
  - make
